# Generated by Django 3.2.3 on 2021-05-20 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210519_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='logo_path',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='logo_path',
        ),
        migrations.RemoveField(
            model_name='work',
            name='snapshot_path',
        ),
        migrations.AddField(
            model_name='contact',
            name='logo',
            field=models.ImageField(null=True, upload_to='contacts/'),
        ),
        migrations.AddField(
            model_name='skill',
            name='icon',
            field=models.ImageField(null=True, upload_to='skills/'),
        ),
        migrations.AddField(
            model_name='work',
            name='screenshot',
            field=models.ImageField(null=True, upload_to='works/'),
        ),
    ]
