# Generated by Django 3.2.3 on 2021-05-20 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210520_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='logo',
            field=models.FileField(null=True, upload_to='contacts/'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.FileField(null=True, upload_to='skills/'),
        ),
        migrations.AlterField(
            model_name='work',
            name='screenshot',
            field=models.FileField(null=True, upload_to='works/'),
        ),
    ]
